[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = [
  "cd nfl-pickem-frontend",
  "npm ci"
]

[phases.build]
cmds = [
  "cd nfl-pickem-frontend", 
  "npm run build"
]

[start]
cmd = "cd nfl-pickem-frontend && npm start"
